# Site settings
title: Zapier Smart Integration
email: boris@smartapartmentdata.com
description: Smart integration with Zapier.
baseurl: "/"
# permalink: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    toc_levels: 1..3

# Exclude
exclude: ['node_modules', 'vendor']
